# Generated by Django 5.1.2 on 2024-11-15 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='raza',
            field=models.CharField(choices=[('Humano', 'Humano'), ('Namekiano', 'Namekiano'), ('Saiyajin', 'Saiyajin')], max_length=10),
        ),
    ]
